trigger:
   - main
   - develop

pool:
   vmImage: windows-2022

steps:
   - task: NodeTool@0
     inputs:
        versionSpec: "16.14.2"
     displayName: "Install Node.js V16"

   - script: |
        npm install
     displayName: "Install dependencies"

   - script: |
        npm run testcli
     displayName: "Run Cypress tests"

   - publish: $(System.DefaultWorkingDirectory)/reports/
     artifact: Cucumber Report
     displayName: "Save Cucumber Reports"

   - download: current
     artifact: Cucumber Report
     displayName: "Download all workflow run artifacts"
