name: Cypress Tests

on:
   push:
      branches:
         - main
         - testing

jobs:
   Cypress-v10-run-tests:
      runs-on: windows-2022
      steps:
         - uses: actions/checkout@v3

         # install a specific version of Node using
         - name: Use Node.js V16
           uses: actions/setup-node@v3
           with:
              node-version: "16.14.2"

         # install and Run Cypress
         - name: Running cypress V10
           id: runningcypress
           uses: cypress-io/github-action@v4
           with:
              config-file: cypress.config.js
              browser: chrome
              headed: true

         - name: Generate Cucumber Report
           if: always()
           run: npm run report

         - name: Save Cucumber Report
           if: always()
           uses: actions/upload-artifact@v3
           with:
              name: Cucumber report ${{ matrix.os }}
              path: reports/

         - name: Save Screenshots Report
           if: failure() && steps.runningcypress.outcome != 'success'
           uses: actions/upload-artifact@v3
           with:
              name: Screenshots report
              path: cypress/screenshots

         - name: Save Video Report
           if: failure() && steps.runningcypress.outcome != 'success'
           uses: actions/upload-artifact@v3
           with:
              name: Video report
              path: cypress/videos

         - name: Download all workflow run artifacts
           if: always()
           uses: actions/download-artifact@v3
