name: E2E Cypress Test GitHub Actions - Windows VM

on:
   push:
      branches:
         - main
         - develop

jobs:
   Cypress-v10-run-tests:
      runs-on: windows-2022
      steps:
         - name: Checkout
           uses: actions/checkout@v3

         - name: Install Node.js V19.6.0
           uses: actions/setup-node@v3
           with:
              node-version: "19.6.0"

         - name: Install dependencies and running Cypress
           id: runningcypress
           uses: cypress-io/github-action@v4
           with:
              config-file: cypress.config.js
              browser: chrome
              headed: true

         - name: Generate Cucumber Report
           if: always()
           run: npm run report

         - name: Save Cucumber Report
           if: always()
           uses: actions/upload-artifact@v3
           with:
              name: cucumber-report
              path: reports/

         - name: Save screenshots if test fails
           uses: actions/upload-artifact@v3
           if: failure()
           with:
              name: cypress-screenshots
              path: cypress/screenshots

         - name: Save video recording always
           uses: actions/upload-artifact@v3
           if: always()
           with:
              name: cypress-videos
              path: cypress/videos
          
